---
- hosts: nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     if [[ ! -e {{ k8s_crt_file }} ]]; then
       kubeadm reset -f
       cat join_token | tail -2 > out.sh
       sh out.sh
     fi
