---
- hosts: masters
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Setup Kubeadm configuration file
    blockinfile:
      path: "{{kubeadm_config_yaml}}"
      create: yes
      block: |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: ClusterConfiguration
        kubernetesVersion: {{kubernetes_version}}
        controlPlaneEndpoint: {{end_point}}:6443
        networking:
          podSubnet: {{cidr_v}}
        clusterName: {{cluster_name}}
        apiServer:
          extraArgs:
            advertise-address: {{ad_addr}}
        ---
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        cgroupDriver: cgroupfs
      state: present

  - name: Initialize Kubernetes Cluster
    shell: kubeadm init --config {{kubeadm_config_yaml}}
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}
    become: False

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f {{ cni_url }}

